# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: autoformat
        name: Check pytest unit tests pass
        entry: pdm run duty format
        pass_filenames: false
        language: system
        types: [ python ]
      - id: lint
        name: Lint with flake8
        entry: pdm run duty check
        pass_filenames: false
        language: system
        exclude: ^(docs/|example-plugin/|tests/fixtures)
        types: [ python ]
      - id: pytest
        name: Check pytest unit tests pass
        entry: pdm run duty test
        pass_filenames: false
        language: system
        types: [ python ]
